dependencies:
    - name: mysql
      version: 0.10.x
      repository: https://kubernetes-charts.storage.googleapis.com/
      condition: mysql.enabled
    - name: redis
      version: 3.6.x
      repository: https://kubernetes-charts.storage.googleapis.com/
    - name: varnish
      version: 1.0.x
      repository: "file://../varnish"
      condition: varnish.enabled
    - name: media-proxy
      version: 1.0.x
      repository: "file://../media-proxy"
      alias: mediaproxy
      condition: mediaproxy.enabled
