dependencies:
    - name: mysql
      version: 1.1.x
      repository: https://kubernetes-charts.storage.googleapis.com/
      condition: mysql.enabled
    - name: redis
      version: 8.0.x
      repository: https://kubernetes-charts.storage.googleapis.com/
    - name: varnish
      version: 1.0.x
      repository: "file://../varnish"
      condition: varnish.enabled
