dependencies:
    - name: mysql
      version: 0.1.x
      repository: https://storage.googleapis.com/t3n-helm-charts
      condition: mysql.enabled
    - name: redis
      version: 10.3.x
      # Repo URL found here with a description why this is necessary https://github.com/bitnami/charts/issues/10539
      repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    - name: varnish
      version: 1.4.x
      repository: "file://../varnish"
      condition: varnish.enabled
    - name: mediaproxy
      version: 1.0.x
      repository: "file://../mediaproxy"
      condition: mediaproxy.enabled
