dependencies:
    - name: mysql
      version: 1.6.x
      repository: https://kubernetes-charts.storage.googleapis.com/
      condition: mysql.enabled
    - name: redis
      version: 10.3.x
      repository: https://kubernetes-charts.storage.googleapis.com/
    - name: varnish
      version: 1.2.x
      repository: "file://../varnish"
      condition: varnish.enabled
