# Default values for sulu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

ingress:
    enabled: true
    annotations: {}
    tls:
        enabled: false
        secretName: ''
        hosts: []
    paths:
        admin: '/admin/*'
        mediaproxy: '/uploads/media/*'
        website: '/*'

# invalidation of cached medias on deletion is not implemented yet
mediaproxy:
    enabled: false

varnish:
    enabled: true
    service:
        type: NodePort
        port: 80
    sessionCookie: PHPSESSID
    # authorization: "user:password"
    # authorizationExcludedUserAgents:
    #   - GoogleHC
    #   - Java
    # vary:
    #   - cookie: "_myCookie"
    #     header: "X-MY-VARY-HEADER"
    # grace: "10m"
    # keep: "1m"
    resources: {}

app:
    deploymentKind: Deployment # or DaemonSet
    replicaCount: 3
    service:
        type: NodePort
        port: 80
    image:
        repository: sulu
        tag: latest
        pullPolicy: IfNotPresent
        pullSecrets:
            enabled: false
            registry: ''
            username: ''
            password: ''
            email: ''
    resources: {}
        # We usually recommend not to specify default resources and to leave this as a conscious
        # choice for the user. This also increases chances charts run on environments with little
        # resources, such as Minikube. If you do want to specify resources, uncomment the following
        # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
        # limits:
        #  cpu: 100m
        #  memory: 128Mi
        # requests:
        #  cpu: 100m
        #  memory: 128Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    annotations: {}
    env: []
    app_env: prod
    email: ''
    secret: ''
    readinessPath: '/'
    readinessAuthentication: false
    hooks:
        postInstall:
            enabled: false
            command: ["/var/www/html/bin/adminconsole", "sulu:build", "dev"]
        postUpgrade:
            enabled: false
            command: ["/var/www/html/bin/adminconsole", "doctrine:migrations:migrate"]
    phpConfig:
        enabled: true
        memoryLimit: 512M
    google:
        enabled: false
        bucket: ''
        project_id: ''
        private_key_id: ''
        private_key: ''
        client_email: ''
        client_id: ''
        client_x509_cert_url: ''

taskrunner:
    enabled: false
    command: ''
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    annotations: {}

mysql:
    enabled: true
    imageTag: 5.7
    mysqlUser: sulu
    # Secret will be recreated on upgrade
    # https://github.com/helm/charts/issues/5167
    mysqlPassword: sulu
    mysqlDatabase: sulu
    persistence:
        enabled: true
        accessMode: ReadWriteOnce
        size: 8Gi

redis:
    # Secret will be recreated on upgrade
    # https://github.com/helm/charts/issues/5167
    password: ''
    cluster:
        enabled: false
