variables:
    HELM_VERSION: 3.4.1

lint:
    stage: lint
    image: dtzar/helm-kubectl:$HELM_VERSION
    script:
        - helm lint elasticsearch
        - helm lint jackrabbit
        - helm lint mediaproxy
        - helm lint sulu
        - helm lint varnish

build:
    stage: build
    image: google/cloud-sdk:slim
    before_script:
        # install helm
        - HELM_SCRIPT_URL=https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        - curl -sSL "$HELM_SCRIPT_URL" | bash -s -- --version "v$HELM_VERSION"
        # authenticate gcloud
        - echo "$SERVICE_ACCOUNT_KEY" > key.json
        - gcloud auth activate-service-account --key-file=key.json
        # download available chart packages
        - mkdir build
        - gsutil cp -r gs://charts.sulu.cloud/* build/ || true
        - helm repo add t3n https://storage.googleapis.com/t3n-helm-charts
    script:
        # create charts
        - helm package -d build elasticsearch
        - helm package -d build jackrabbit
        - helm package -d build mediaproxy
        - cd sulu && helm dep build && cd .. && helm package -d build sulu
        - helm package -d build varnish
        # index directory
        - helm repo index build
    after_script:
        # upload new packaged charts
        - gsutil -h "Cache-Control:no-cache,max-age=0" cp build/* gs://charts.sulu.cloud/
    only:
        - master

stages:
    - lint
    - build
