variables:
    HELM_VERSION: 3.10.1

lint:
    stage: lint
    image: dtzar/helm-kubectl:$HELM_VERSION
    script:
        - helm dependency build elasticsearch
            && helm dependency list elasticsearch
            && helm lint elasticsearch --strict
            && helm template elasticsearch > template-result-elasticsearch.yaml
        - helm dependency build jackrabbit
            && helm dependency list jackrabbit
            && helm lint jackrabbit --strict
            && helm template jackrabbit > template-result-jackrabbit.yaml
        - helm dependency build mediaproxy
            && helm dependency list mediaproxy
            && helm lint mediaproxy --strict
            && helm template mediaproxy > template-result-mediaproxy.yaml
        - helm dependency build sulu
            && helm dependency list sulu
            && helm lint sulu --strict
            && helm template sulu > template-result-sulu.yaml
        - helm dependency build varnish
            && helm dependency list varnish
            && helm lint varnish --strict
            && helm template varnish > template-result-varnish.yaml
    artifacts:
        name: template-results
        paths:
            - template-result-*.yaml

build:
    stage: build
    image: google/cloud-sdk:slim
    before_script:
        # install helm
        - HELM_SCRIPT_URL=https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        - curl -sSL "$HELM_SCRIPT_URL" | bash -s -- --version "v$HELM_VERSION"
        # authenticate gcloud
        - echo "$SERVICE_ACCOUNT_KEY" > key.json
        - gcloud auth activate-service-account --key-file=key.json
    script:
        # download existing charts
        - mkdir build
        - gsutil cp -r gs://charts.sulu.cloud/* build/ || true
        # package new charts
        - helm dependency build elasticsearch && helm package --destination build elasticsearch
        - helm dependency build jackrabbit && helm package --destination build jackrabbit
        - helm dependency build mediaproxy && helm package --destination build mediaproxy
        - helm dependency build sulu && helm package --destination build sulu
        - helm dependency build varnish && helm package --destination build varnish
        # index charts directory
        - helm repo index build
        # upload updated charts and index
        - gsutil -h "Cache-Control:no-cache,max-age=0" cp build/* gs://charts.sulu.cloud/
    only:
        - master

stages:
    - lint
    - build
