lint:
    stage: lint
    image: sulu/helm-gcloud
    script:
        - helm lint varnish
        - helm lint sulu

build:
    stage: build
    image: sulu/helm-gcloud
    before_script:
        # authenticate gcloud
        - echo "$SERVICE_ACCOUNT_KEY" > key.json
        - gcloud auth activate-service-account --key-file=key.json
        # download available chart packages
        - mkdir build
        - gsutil cp -r gs://charts.sulu.cloud/* build/ || true
    script:
        # create charts
        - helm package -d build varnish
        - cd sulu && helm dep build && cd ..
        - helm package -d build sulu
        # index directory
        - helm repo index build
    after_script:
        # upload new packaged charts
        - gsutil cp build/* gs://charts.sulu.cloud/
    only:
        - master

stages:
    - lint
    - build
