variables:
    HELM_VERSION: 3.5.1

lint:
    stage: lint
    image: dtzar/helm-kubectl:$HELM_VERSION
    script:
        - helm dependency build elasticsearch && helm lint elasticsearch
        - helm dependency build jackrabbit && helm lint jackrabbit
        - helm dependency build mediaproxy && helm lint mediaproxy
        - helm dependency build sulu && helm lint sulu
        - helm dependency build varnish && helm lint varnish

build:
    stage: build
    image: google/cloud-sdk:slim
    before_script:
        # install helm
        - HELM_SCRIPT_URL=https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        - curl -sSL "$HELM_SCRIPT_URL" | bash -s -- --version "v$HELM_VERSION"
        # authenticate gcloud
        - echo "$SERVICE_ACCOUNT_KEY" > key.json
        - gcloud auth activate-service-account --key-file=key.json
    script:
        # download existing charts
        - mkdir build
        - gsutil cp -r gs://charts.sulu.cloud/* build/ || true
        # package new charts
        - helm dependency build elasticsearch && helm package -d build elasticsearch
        - helm dependency build jackrabbit && helm package -d build jackrabbit
        - helm dependency build mediaproxy && helm package -d build mediaproxy
        - helm dependency build sulu && helm package -d build sulu
        - helm dependency build varnish && helm package -d build varnish
        # index charts directory
        - helm repo index build
        # upload updated charts and index
        - gsutil -h "Cache-Control:no-cache,max-age=0" cp build/* gs://charts.sulu.cloud/        
    only:
        - master

stages:
    - lint
    - build
