lint:
    stage: lint
    image: sulu/helm-gcloud:2.13.1-buster
    script:
        - helm lint elasticsearch
        - helm lint jackrabbit
        - helm lint mediaproxy
        - helm lint sulu
        - helm lint varnish

build:
    stage: build
    image: sulu/helm-gcloud:2.13.1-buster
    before_script:
        # authenticate gcloud
        - echo "$SERVICE_ACCOUNT_KEY" > key.json
        - gcloud auth activate-service-account --key-file=key.json
        # download available chart packages
        - mkdir build
        - gsutil cp -r gs://charts.sulu.cloud/* build/ || true
    script:
        # create charts
        - helm package -d build elasticsearch
        - helm package -d build jackrabbit
        - helm package -d build mediaproxy
        - cd sulu && helm dep build && cd .. && helm package -d build sulu
        - helm package -d build varnish
        # index directory
        - helm repo index build
    after_script:
        # upload new packaged charts
        - gsutil cp build/* gs://charts.sulu.cloud/
    only:
        - master

stages:
    - lint
    - build
