{{- if (eq "StatefulSet" .Values.kind) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "varnish.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "varnish.name" . }}-headless
    helm.sh/chart: {{ include "varnish.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "varnish.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
