{{- if (eq "StatefulSet" .Values.kind) -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "varnish.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "varnish.fullname" . }}
    helm.sh/chart: {{ include "varnish.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: {{ include "varnish.fullname" . }}-headless
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "varnish.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  updateStrategy:
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "varnish.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: {{ include "varnish.fullname" . }}
      volumes:
      - name: {{ .Release.Name }}-varnish-configmap
        configMap:
          name: {{ .Release.Name }}-varnish-configmap
          items:
          - key: default.vcl
            path: default.vcl
      containers:
      - name: {{ include "varnish.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
{{- with .Values.image.args }}
{{ toYaml . | indent 10 }}
{{- end }}
        env:
        - name: VARNISH_SIZE
          value: {{ .Values.varnishSize }}
{{- with .Values.env }}
{{ toYaml . | indent 8 }}
{{- end }}
        volumeMounts:
        - name: {{ .Release.Name }}-varnish-configmap
          mountPath: /etc/varnish/
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
