{{- if .Values.app.google.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "sulu.fullname" . }}-google-config
    labels:
        app: {{ template "sulu.fullname" . }}
        helm.sh/chart: {{ include "sulu.chart" . }}
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
data:
    key.json: |-
{{ $file := (.Files.Get "config/google-key.json") }}
{{ tpl $file . | indent 8 }}
{{- end }}
