{{- if .Values.app.image.pullSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ template "sulu.image_pull_secrets.name" . }}
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: {{ template "sulu.image_pull_secrets" . }}
{{- end }}
