{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: {{ include "sulu.fullname" . }}-ingress
    labels:
        app.kubernetes.io/name: {{ include "sulu.name" . }}
        helm.sh/chart: {{ include "sulu.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
    annotations:
{{ toYaml . | indent 8 }}
{{- end }}
spec:
    rules:
{{- range .Values.ingress.tls.hosts }}
        - http:
              paths:
                  - path: {{ $.Values.ingress.paths.admin }}
                    backend:
                        serviceName: {{ include "sulu.fullname" $ }}
                        servicePort: http
{{- if $.Values.mediaproxy.enabled }}
                  - path: {{ $.Values.ingress.paths.mediaproxy }}
                    backend:
                        serviceName: {{ include "sulu.mediaproxy.fullname" $ }}
                        servicePort: http
{{- end }}
                  - path: {{ $.Values.ingress.paths.website }}
                    backend:
                        serviceName: {{ include "sulu.varnish.fullname" $ }}
                        servicePort: http
          host: {{ . }}
{{- end }}
{{- if .Values.ingress.tls.enabled }}
    tls:
        - secretName: {{ .Values.ingress.tls.secretName }}
          hosts:
{{- with .Values.ingress.tls.hosts }}
{{ toYaml . | indent 14 }}
{{- end }}
{{- end }}
{{- end }}
