apiVersion: apps/v1
kind: {{ .Values.app.deploymentKind }}
metadata:
  name: {{ include "sulu.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sulu.name" . }}
    helm.sh/chart: {{ include "sulu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if ne .Values.app.deploymentKind "DaemonSet" }}
  replicas: {{ .Values.app.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sulu.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sulu.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{ include "sulu.container.spec.tpl" . | indent 6 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: {{ .Values.app.readinessPath }}
              port: http
{{- if .Values.app.readinessAuthentication }}
              httpHeaders:
                - name: Authorization
                  value: Basic {{ .Values.app.readinessAuthentication|b64enc }}
{{- end }}
          resources:
{{ toYaml .Values.app.resources | indent 12 }}
    {{- with .Values.app.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.app.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.app.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
