{{- if .Values.taskrunner.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sulu.taskrunner.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sulu.name" . }}
    helm.sh/chart: {{ include "sulu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sulu.taskrunner.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sulu.taskrunner.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{ include (print $.Template.BasePath "/_containerspec.tpl") . | indent 6 }}
          command: [{{ .Values.taskrunner.command | quote }}]
          resources:
{{ toYaml .Values.taskrunner.resources | indent 12 }}
    {{- with .Values.taskrunner.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.taskrunner.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.taskrunner.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
