apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mediaproxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mediaproxy.name" . }}
    helm.sh/chart: {{ include "mediaproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: {{ include "mediaproxy.fullname" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mediaproxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "mediaproxy.fullname" . }}-data
    spec:
      accessModes:
      {{- range .Values.persistence.accessModes }}
        - {{ . | quote }}
      {{- end }}
      {{ include "mediaproxy.storageClass" . }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
  updateStrategy:
    type: {{ .Values.statefulset.updateStrategy }}
    {{- if .Values.statefulset.rollingUpdatePartition }}
    {{- if (eq "Recreate" .Values.statefulset.updateStrategy) }}
    rollingUpdate: null
    {{- else }}
    rollingUpdate:
      partition: {{ .Values.statefulset.rollingUpdatePartition }}
    {{- end }}
    {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mediaproxy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
      - name: {{ include "mediaproxy.fullname" . }}-configmap
        configMap:
          name: {{ include "mediaproxy.fullname" . }}-configmap
          items:
          - key: nginx.conf
            path: mediaproxy.conf
      initContainers:
      - name: volume-permissions
        image: busybox
        # https://github.com/docker-library/docs/tree/master/nginx#user-and-group-id
        command: ["sh", "-c", "chown -R 101:101 /usr/share/mediaproxy/data"]
        volumeMounts:
        - name: {{ include "mediaproxy.fullname" . }}-data
          mountPath: /usr/share/mediaproxy/data
      containers:
      - name: {{ include "mediaproxy.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.env }}
        env:
{{- with .Values.env }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
        volumeMounts:
        - name: {{ include "mediaproxy.fullname" . }}-data
          mountPath: /var/nginx/cache
        - name: {{ include "mediaproxy.fullname" . }}-configmap
          mountPath: /etc/nginx/conf.d
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
