apiVersion: v1
appVersion: "2.20.2"
description: A Helm chart for Jackrabbit
name: jackrabbit
version: 1.1.0
maintainers:
    - name: 'Johannes Wachter'
      email: johannes@sulu.io
    - name: 'Thomas Schedler'
      email: thomas@sulu.io
